export const data = {
  // test
  telangana: [
    {
      name: "Parlapally",
      pdf: "/Assets/parlapally/pdf.pdf",
      profileImg: "/Assets/parlapally/profile.jpg",
      profileName: "Dr.Anupama",
      images: [
        "./Assets/parlapally/img (1).jpg",
        "./Assets/parlapally/img (2).jpg",
        "./Assets/parlapally/img (3).jpg",
        "./Assets/parlapally/img (4).jpg",
        "./Assets/parlapally/img (5).jpeg",
        "./Assets/parlapally/img (6).jpg",
        "./Assets/parlapally/img (7).jpg",
        "./Assets/parlapally/img (8).jpg",
        "./Assets/parlapally/img (9).jpg",
        "./Assets/parlapally/img (10).jpg",
        "./Assets/parlapally/img (11).jpg",
        "./Assets/parlapally/img (12).jpg",
        "./Assets/parlapally/img (13).jpg",
        "./Assets/parlapally/img (14).jpg",
        "./Assets/parlapally/img (15).jpg",
        "./Assets/parlapally/img (16).jpg",
        "./Assets/parlapally/img (17).jpg",
        "./Assets/parlapally/img (18).jpg",
        "./Assets/parlapally/img (19).jpg",
        "./Assets/parlapally/img (20).jpg",
        "./Assets/parlapally/img (21).jpg",
        "./Assets/parlapally/img (22).jpg",
      ],
    },
    {
      name: "Buddaram",
      pdf: "/Assets/buddaram/pdf.pdf",
      profileImg: "/Assets/buddaram/profile.jpg",
      profileName: "Dr.Ambatpalli Sarojini Rao",
      images: [
        "./Assets/buddaram/img (1).jpg",
        "./Assets/buddaram/img (1).png",
        "./Assets/buddaram/img (3).jpg",
        "./Assets/buddaram/img (4).jpg",
        "./Assets/buddaram/img (5).jpg",
        "./Assets/buddaram/img (6).jpg",
        "./Assets/buddaram/img (7).jpg",
        "./Assets/buddaram/img (8).jpg",
        "./Assets/buddaram/img (9).jpg",
      ],
    },
  ],
  gujrat: [],
  andhrapradesh: [],
  karnataka: [],
};
